### ISSUE TITLE
In quiz, "Review attempt" render the code in a more readable way

### ISSUE THREAD

**Issue by lucaboesch** [bschur/moodle-qtype_uml#80]
This
<img width="799" alt="image" src="https://github.com/bschur/moodle-qtype_uml/assets/377279/2ff6775d-f569-4022-bdd5-3078ac0473ad">
should be copy-pastable readable XML.

**Comment by arisjavet-personal** [comment]
Hey Luca

Thanks for the ticket. 

I don't think that Moodle currently supports this customization or at least I found nothing in the internet.
The code, which is responsible for this code, lays in the `engine/renderer.php` itself. From a plugins code we have no option to override this code. Our renderer has the following inheritance structure: `qtype_uml_renderer -> qtype_renderer -> plugin_renderer_base -> renderer_base`.

I only found out that Moodle lets you disable the history this setting would be globally though. Here the link to the old thread: [https://moodle.org/mod/forum/discuss.php?d=213905](https://moodle.org/mod/forum/discuss.php?d=213905)

Another old thread with an similar requirement to ours: [https://moodle.org/mod/forum/discuss.php?d=278920](https://moodle.org/mod/forum/discuss.php?d=278920)

Do you perhaps know a way or know a plugin which has somehow managed to customize this view?

A way I could image is just customize it with JavaScript but that would be an ugly workaround :|
